version: '3'

services:
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oreoreo
      POSTGRES_DB: codingpup
      PGUSER: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: codinpup
      DB_USER: priyanka
      DB_PASSWORD: oreoreo